name: Snap CI
on:
  schedule:
    - cron: "20 2 * * 1" # Monday mornings at 02:20 UTC
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual trigger
  workflow_dispatch:

env:
  SNAP_NAME: matter-all-clusters-app

jobs:
  build:
    name: Build, Publish
    strategy:
      matrix:
        runs:
          - architecture: amd64
            runner: ubuntu-latest
          - architecture: arm64
            runner: [self-hosted, ARM64, Linux]
    runs-on: ${{ matrix.runs.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.SNAP_NAME}}_${{github.run_number}}_${{matrix.runs.architecture}}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error

      - name: Publish snap to edge
        uses: snapcore/action-publish@v1
        # if: github.ref == 'refs/heads/main'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: latest/edge/test
